name: reviewdog
on:
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    name: runner / chore
    runs-on: ["gha-runner-scale-set"]
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@v1.16.25
        with:
          files: ./docs
